### ISSUE TITLE
Plan to continue polish extension doc

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-docs#2199]
We would like to publish the revamped https://vscode-ext-docs.azurewebsites.net/api for November iteration.

Following the work we did at https://github.com/Microsoft/vscode-docs/issues/1949, we continue to do the minimal amount of work to get the API extension out. After publishing, we would create a backlog of nice-to-have topics / enhancements and tackle them on an availability basis.

- [x] Guide / Sample for using Commands #2189 @mjbvz 
- [x] 💪Color Theme Guide #2197 @Tyriar 
- [x] Preliminary Guide / Sample for writing a TextMate Grammar #2188 @mjbvz
- [x] Snippets Guide / Sample #2187 @octref 
- [x] Language Configuration Guide / Sample #2186 @rebornix 
- [x] Debugger Guide update #2195 @weinand
- [x] TreeView Guide update #2194 @sandy081 
- [x] Find a good place for content in Principles and Patterns #2203 @kieferrm @jrieken 
---

Chores:

- [x] Fix table auto-generation #2210 @octref
- [x] Update old links pointing to /docs/extensions and /docs/extensionAPI #2165 @octref
- [x] Port /docs/extension* master changes to ext-doc branch topics #2238 @gregvanl 
- [x] Change HelloCode back to HelloWorld #2144 @octref

Assignees: Please start early so your reviewers have time to provide feedback. 

We'll continue to address feedback for the existing documentation, but there is no plan item for them. If you do have feedback for our [Preview API Doc](https://vscode-ext-docs.azurewebsites.net/api), please open new issues and ping me.

## Deferred

- [ ] 🏃Split LSP Guide into Smart Editing Guide and Smart Editing LSP Guide #2209 @octref
- [ ] 💪Add ability to click-to-maximize pictures #2162 @octref

**Comment by octref** [comment]
Shipped.
