### ISSUE TITLE
December Doc-a-thon

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#702]
The goal is to identify missing, stale or obsolete content in the main VS Code docs.

You can:

1. Enter a vscode-docs issue describing the necessary change or addition.
2. Enter an issue and point to relevant existing content to port (release notes, issue comment, protocol or sample repo content).
3. Create or update content and submit a PR against vscode-docs master.

Topics

-----
@gregvanl New topics that need a home:
- **deferred** Keyboard Layouts @alexandrudima
- [x] Extensions that are only available to insiders @joaomoreno
- [x] Extension Authoring>[Extension Packs](https://code.visualstudio.com/docs/extensionAPI/extension-manifest#_extension-packs) @sandy081
- [x] Recommended Extensions @sandy081
- [x] Customization>File icons @aeschli
- [x] Hot Exit @tyriar
- [x] Promote Go to the same level as other languages in the docs, PHP, Python etc. @ramya-rao-a
- [ ] (initial progress) Editor Architecture @rebornix
-----

Setup

- [x] Overview @chrmarti
- [x] Windows @ramya-rao-a
- [x] Mac @chrmarti
- [x] Linux @Tyriar
- [x] Additional Components @chrmarti

Editor

- [x] The Basics 
  - [x] @rebornix 
  - [x] @chrmarti
- [x] Extension Marketplace @joaomoreno
- [ ] IntelliSense 
  - [x] @mjbvz 
  - [ ] @waderyan [vscode-docs #742](https://github.com/Microsoft/vscode-docs/issues/742)
- [ ] Editing Evolved 
  - [ ] @alexandrudima 
  - [x] @ramya-rao-a
- [ ] Debugging 
  - [ ] @weinand 
  - [ ] @isidorn 
  - [x] @roblourens
- [x] Version Control @joaomoreno
- [x] Tasks @dbaeumer
- [x] Integrated Terminal@Tyriar
- [x] Tabs @bpasero
- [ ] Accessibility 
  - [ ] @alexandrudima 
  - [x] @rebornix
- [x] Why VS Code @mousetraps

Customization

- [x] Overview @sandy081
- [x] User and Workspace Settings @sandy081
- [ ] Key Bindings @alexandrudima
- [x] Snippets @jrieken
- [x] Colorizer @aeschli
- [x] Themes @aeschli
- [x] Display Language 
  - [x] @dbaeumer 
  - [x] @ramya-rao-a

Languages

- [x] Overview @ramya-rao-a
- [x] JavaScript  (including the [jsconfig.json](https://code.visualstudio.com/docs/languages/jsconfig)) section 
  - [x] @waderyan [vscode-docs #740](https://github.com/Microsoft/vscode-docs/issues/740)
  - [x] @mjbvz 
  - [ ] @egamma
- [x] JSON @aeschli
- [x] HTML @aeschli
- [ ] PHP @mousetraps
- [ ] Python @waderyan [vscode-docs #739](https://github.com/Microsoft/vscode-docs/issues/739)
- [x] Markdown @mjbvz
- [x] TypeScript 
  - [x] @dbaeumer 
  - [x] @mjbvz
- [x] CSS, Sass, and Less @aeschli
- [x] Dockerfile @chrisdias

Runtimes

- [x] Node.js 
  - [x] @chrisdias 
  - [x] @egamma

Extension Authoring

- [x] Overview @rebornix
- [x] Example - Hello World @alexandrudima
- [x] Example - Word Count @alexandrudima
- [x] Example - Language Server @dbaeumer
- [ ] Example - Debuggers
  - [ ]  @weinand 
  - [x] @roblourens
- [x] Principles and Patterns 
  - [x] @jrieken 
  - [x] @rebornix
- [ ] Language Extension Guidelines
  - [x] @dbaeumer
  - [ ] @jrieken 
  - [x] @aeschli 
- [x] Running and Debugging Extensions @bpasero
- [x] Installing Extensions @joaomoreno
- [x] Testing Extensions @bpasero
- [x] Our Approach @rebornix

Extensibility Reference

- [x] Overview @rebornix
- [x] Extension Manifest @joaomoreno 
- [x] Contribution Points @jrieken
- [x] Activation Events @jrieken
- [ ] API debugging 
  - [ ] @weinand  

Tools

- [x] Publishing Tool @joaomoreno
- [x] Extension Generator 
  - [x] @aeschli 
  - [x] @chrmarti
- [x] Samples @ramya-rao-a

GitHub
- [x] [Tips and Tricks Repo](https://github.com/Microsoft/vscode-tips-and-tricks) @waderyan [vscode-docs #743](https://github.com/Microsoft/vscode-docs/issues/743)

**Comment by dbaeumer** [comment]
We have quite some satellite npm modules which maintain documentation as well. We should include this in a doc-a-thon. Mine are:

vscode-languageserver-node: https://github.com/Microsoft/vscode-languageserver-node
language-server-protocol: https://github.com/Microsoft/language-server-protocol 
vscode-nls: https://github.com/Microsoft/vscode-nls
vscode-nls-dev: https://github.com/Microsoft/vscode-nls-dev

**Comment by dbaeumer** [comment]
@gregvanl for  `Language Extension Guidelines` I added @aeschli and @jrieken as well. I can perfectly handle the LSP part in there but the other parts are better handled by @aeschli and @jrieken.

**Comment by aeschli** [comment]
@gregvanl File icons are already documented on the themes page. The content is still up-to-date

**Comment by sandy081** [comment]
@gregvanl Here is the PR for updating user and workspace settings documentation

https://github.com/Microsoft/vscode-docs/pull/749

**Comment by dbaeumer** [comment]
Created https://github.com/Microsoft/vscode-docs/pull/760

**Comment by aeschli** [comment]
I've checked off all my items (just in case they uncheck themselves again).

Also I added a new sample: [language provider sample](https://github.com/Microsoft/vscode-extension-samples/commit/170f24add1a6a37dfe9f1fd3b9e29a3fe29caceb), that brings the existing [language server example](https://github.com/Microsoft/vscode-languageserver-node-example) to the extension sample projects. I improved the structure and added a compound launch config (launch client and attach server).
Please feel free to improve further. I'm off until after XMas. Happy holidays!

**Comment by joaomoreno** [comment]
I've checked off all my items (just in case they uncheck themselves again).

**Comment by chrisdias** [comment]
docker and node done!
