### ISSUE TITLE
   https://g.co/kgs/9t38Hxw

### ISSUE THREAD

**Issue by Alnahrclean** [microsoft/vscode-docs#7293]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-docs/issues/7289
- [ ] https://github.com/microsoft/vscode-docs/issues/7292
- [ ] https://github.com/microsoft/vscode-docs/issues/7291
- [ ] https://github.com/microsoft/vscode-docs/issues/7252
- [ ] https://github.com/microsoft/vscode-docs/pull/5332
- [ ] https://github.com/microsoft/vscode-docs/issues/7288
- [ ] https://github.com/microsoft/vscode-docs/pull/7290
- [ ] https://github.com/microsoft/vscode-docs/pull/7286
- [ ] https://github.com/microsoft/vscode-docs/pull/7114
- [ ] https://github.com/microsoft/vscode-docs/issues/7107
- [ ] https://github.com/microsoft/vscode-docs/pull/7260
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-docs/issues/7292
- [ ] cp.mohamed.1993@gmail.com
- [ ] https://github.com/microsoft/vscode-docs/issues/7289
- [ ] https://github.com/microsoft/vscode-docs/issues/7291
- [ ] https://github.com/microsoft/vscode-docs/issues/7287
- [ ] https://github.com/microsoft/vscode-docs/issues/7288
- [ ] https://github.com/microsoft/vscode-docs/pull/7286
```

**Comment by Alnahrclean** [comment]
شركة النهر لصيانةأجهزةالتكييف في دبي
