### ISSUE TITLE
DJANGO

### ISSUE THREAD

**Issue by femenza** [microsoft/vscode-docs#7426]
It looks like this is your first time opening an issue in this project!

Be sure to review thehttps://github.com/microsoft/vscode-docs/issues/6874#issue-2022146513Reporting a security vulnerability?
Check out the project's [security policy](https://github.com/microsoft/vscode-docs/security/policy).
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-docs/issues/5215
- [ ] https://github.com/microsoft/vscode-docs/pull/7424
- [ ] https://github.com/microsoft/vscode-docs/issues/7359
- [ ] https://github.com/microsoft/vscode-docs/pull/7397
- [ ] https://github.com/microsoft/vscode-docs/issues/7344
- [ ] https://github.com/microsoft/vscode-docs/issues/7412
- [ ] https://github.com/microsoft/vscode-docs/issues/7276
- [ ] https://github.com/microsoft/vscode-docs/issues/7406
- [ ] https://github.com/microsoft/vscode-docs/issues/7417
- [ ] https://github.com/microsoft/vscode-docs/issues/7408
- [ ] https://github.com/microsoft/vscode-docs/issues/7411
- [ ] https://github.com/microsoft/vscode-docs/issues/7418
- [ ] https://github.com/microsoft/vscode-docs/issues/7416
- [ ] https://github.com/microsoft/vscode-docs/issues/7414
```

**Comment by femenza** [comment]
GOOD
