### ISSUE TITLE
wsl

### ISSUE THREAD

**Issue by carasen12** [microsoft/vscode-docs#7583]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-docs/issues/7582
- [ ] https://github.com/microsoft/vscode-docs/issues/7579
- [ ] https://github.com/microsoft/vscode-docs/pull/7581
- [ ] https://github.com/microsoft/vscode-docs/issues/7576
- [ ] https://github.com/microsoft/vscode-docs/pull/7580
- [ ] https://github.com/microsoft/vscode-docs/pull/7577
```
